CREATE TABLE shortened_urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_deleted   BOOLEAN                                 NOT NULL,
    original_url TEXT                                    NOT NULL,
    short_key    VARCHAR(10)                             NOT NULL,
    click_count  BIGINT                                  NOT NULL,
    expires_at   BIGINT,
    CONSTRAINT pk_shortened_urls PRIMARY KEY (id)
);

ALTER TABLE shortened_urls
    ADD CONSTRAINT uc_shortened_urls_short_key UNIQUE (short_key);

CREATE INDEX idx_short_key ON shortened_urls (short_key);